name: WaterWorld
version: 2.5
main: com.dagxam.waterworld.WaterWorldPlugin
api-version: '26.2'
load: STARTUP
description: Основной мир сервера генерируется WaterWorld: остров, океан, плавные берега, растительность и животные.
