name: WaterWorld
version: 2.3
main: com.dagxam.waterworld.WaterWorldPlugin
api-version: '26.2'
load: STARTUP
description: Большой остров и дополнительные острова в бескрайнем океане с плавным берегом, растительностью и животными.
