name: WaterWorld
version: 2.7
main: com.dagxam.waterworld.WaterWorldPlugin
api-version: '26.2'
load: STARTUP
description: "Основной мир сервера генерируется WaterWorld. Чистый океан, один главный остров, малые острова, плавные берега, растительность и животные."
